/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef, useState, useEffect, useMemo} from 'react'
import { button, useControls } from 'leva'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { useFrame} from '@react-three/fiber';

import * as THREE from 'three';

// Quaternion that rotates -90° around X (converts Z-up FBX "With Skin" → Y-up Three.js)
const ARMATURE_Q = new THREE.Quaternion(-Math.SQRT1_2, 0, 0, Math.SQRT1_2);
import { useChat } from "../hooks/useChat";

import { lipsyncManager } from "../App"; 
import { VISEMES } from "wawa-lipsync";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};



export function Avatar(props) {
  // Load the GLTF model 
  const { nodes, materials } = useGLTF('/models/689efc72bf8e07103aba1faa.glb');

  // Handle chat messages and Lipsync
  const { message, onMessagePlayed, onShowTextAfterAudio, chat, phase } = useChat();
  const [isSetupMode, setIsSetupMode] = useState(false);

  // Create a ref to hold the cached list
  const morphMeshesRef = useRef([]);

  // add a ref to stop previous audio
  const audioRef = useRef(null);

  const visemes = Array.isArray(VISEMES) ? VISEMES : Object.values(VISEMES);
  // Fallbacks if the runtime returns letters/indices
  const index_to_letter = ["A","B","C","D","E","F","G","H","X"];
  const letter_to_name = {
    A:"viseme_PP", B:"viseme_kk", C:"viseme_I", D:"viseme_AA",
    E:"viseme_O",  F:"viseme_U",  G:"viseme_FF", H:"viseme_TH",
    X:null
  };

  // Handle lipsync + audio playback with cleanup and overlap prevention
  useEffect(() => {
    if (!message) {
      setAnimation("Idle");
      return;
    }

    // stop and clean previous audio if any
    if (audioRef.current) {
      audioRef.current.onended = null;
      audioRef.current.pause();

      // release the data URL to help GC in some browsers
      audioRef.current.src = "";
      audioRef.current = null;
    }

    // Animations that trigger during audio rather than at the start:
    // - PresentingRecommendations: 2 seconds before audio ends
    // - Thankful: at the midpoint of audio
    const pendingAnimation = message.animation;
    const DELAYED_ANIMS = {
      PresentingRecommendations: (dur) => Math.max(0, (dur - 2) * 1000),
      ...(phase === 1 && { Thankful: (dur) => (dur / 3) * 1000 }),
    };
    const isDelayed = pendingAnimation in DELAYED_ANIMS;
    setAnimation(isDelayed ? "Idle" : pendingAnimation);
    setFacialExpression(message.facialExpression);

    if (!message.audio) {
      if (isDelayed) setAnimation(pendingAnimation);
      onShowTextAfterAudio?.();
      onMessagePlayed?.();
      return;
    }

    const audio = new Audio("data:audio/mp3;base64," + message.audio);
    audioRef.current = audio;
    try { lipsyncManager.connectAudio(audioRef.current); } catch {}

    let midTimer = null;
    if (isDelayed) {
      audio.addEventListener("loadedmetadata", () => {
        const delayMs = DELAYED_ANIMS[pendingAnimation](audio.duration);
        midTimer = setTimeout(() => setAnimation(pendingAnimation), delayMs);
      }, { once: true });
    }

    audioRef.current.play().catch((err) => {
      console.error("Audio play error:", err);
      clearTimeout(midTimer);
      onShowTextAfterAudio?.();
      onMessagePlayed?.();
    });

    audioRef.current.onended = () => {
      clearTimeout(midTimer);
      onShowTextAfterAudio?.();
      onMessagePlayed?.();
    };
    // cleanup if a new message arrives or component unmounts mid-play
    return () => {
      clearTimeout(midTimer);
      if (audioRef.current) {
        audioRef.current.onended = null;
        audioRef.current.pause();
        audioRef.current.src = "";
        audioRef.current = null;
      }
    };

  }, [message, onMessagePlayed, phase]);
  

  // Load animations
  const {animations: idleAnimation} = useFBX('/animations/Idle.fbx');
  const {animations: idleChillingAnimation} = useFBX('/animations/IdleChilling.fbx');
  const {animations: greetingAnimation} = useFBX('/animations/Greeting.fbx');
  const {animations: thankfulAnimation} = useFBX('/animations/Thankful.fbx');
  const {animations: acknowledgingAnimation} = useFBX('/animations/Acknowledging.fbx');
  const {animations: presentingRecommendationsAnimation} = useFBX('/animations/PresentingRecommendations.fbx');


  // Prepare the group for animations
  const group = useRef();
  idleAnimation[0].name = 'Idle';
  idleChillingAnimation[0].name = 'IdleChilling';
  greetingAnimation[0].name = 'Greeting';
  thankfulAnimation[0].name = 'Thankful';
  acknowledgingAnimation[0].name = 'Acknowledging';
  presentingRecommendationsAnimation[0].name = 'PresentingRecommendations';

  const animationClips = useMemo(() => {
    const tmp = new THREE.Quaternion();
    return [idleAnimation[0], idleChillingAnimation[0], greetingAnimation[0], thankfulAnimation[0], acknowledgingAnimation[0], presentingRecommendationsAnimation[0]]
      .map(clip => {
        const c = clip.clone();

        // Detect Z-up export: first Hips position keyframe has |Z| >> |Y|
        const hipsPosTrack = c.tracks.find(t => /hips\.position/i.test(t.name));
        const isZUp = hipsPosTrack && Math.abs(hipsPosTrack.values[2]) > 0.5 && Math.abs(hipsPosTrack.values[2]) > Math.abs(hipsPosTrack.values[1]) * 5;

        console.log(`[Avatar] ${clip.name} — isZUp: ${isZUp}`);

        if (!isZUp) return c;

        c.tracks = c.tracks.flatMap(track => {
          // Remove Armature tracks — no matching node in the GLTF avatar
          if (/^armature\./i.test(track.name)) return [];

          // Convert Hips position from Z-up to Y-up: (x,y,z) → (x, z, -y)
          if (/hips\.position/i.test(track.name)) {
            for (let i = 0; i < track.values.length; i += 3) {
              const y = track.values[i + 1];
              const z = track.values[i + 2];
              track.values[i + 1] = z;
              track.values[i + 2] = -y;
            }
            return [track];
          }

          // Bake missing Armature rotation into Hips quaternion: new_q = ARMATURE_Q * old_q
          if (/hips\.quaternion/i.test(track.name)) {
            for (let i = 0; i < track.values.length; i += 4) {
              tmp.set(track.values[i], track.values[i + 1], track.values[i + 2], track.values[i + 3]);
              tmp.premultiply(ARMATURE_Q);
              track.values[i]     = tmp.x;
              track.values[i + 1] = tmp.y;
              track.values[i + 2] = tmp.z;
              track.values[i + 3] = tmp.w;
            }
            return [track];
          }

          return [track];
        });

        return c;
      });
  }, [idleAnimation, idleChillingAnimation, greetingAnimation, thankfulAnimation, acknowledgingAnimation, presentingRecommendationsAnimation]);

  // Hook animations to the rendered group
  const [animation, setAnimation] = useState('Idle');
  const {actions, mixer} = useAnimations(
      animationClips,
      group
  );

  // Animations that play once then fall back to Idle
  const ONCE_ANIMATIONS = new Set(["Greeting", "Thankful", "PresentingRecommendations"]);

  // Handle animation changes
  useEffect(() => {
    if (!actions || !animation) return;
    Object.values(actions).forEach(a => a?.fadeOut?.(0.3));
    const action = actions[animation];
    if (!action) return;

    if (ONCE_ANIMATIONS.has(animation)) {
      action.setLoop(THREE.LoopOnce, 1);
      action.clampWhenFinished = true;
      action.reset().fadeIn(0.3).play();
      const onFinished = (e) => {
        if (e.action === action) {
          mixer.removeEventListener("finished", onFinished);
          actions["Idle"]?.reset().fadeIn(0.3).play();
        }
      };
      mixer.addEventListener("finished", onFinished);
      return () => {
        action.fadeOut(0.3);
        mixer.removeEventListener("finished", onFinished);
      };
    }

    action.reset().fadeIn(0.3).play();
    return () => {
      action.fadeOut(0.3);
    };
  }, [actions, animation, mixer]);


  // Handle Head Follow
  const headRef = useRef(null);
  useEffect(() => {
    if (!group.current) return;
    headRef.current = group.current.getObjectByName("Head");
  }, [nodes]); // runs after model is ready

  useFrame((state) => {
    headRef.current?.lookAt(state.camera.position);
  });

  // fter the model is mounted, collect morphable meshes once
  useEffect(() => {
    if (!group.current) return;
    const list = [];
    group.current.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary && child.morphTargetInfluences) {
        list.push({
          dict: child.morphTargetDictionary,
          infl: child.morphTargetInfluences,
        });
      }
    });

    morphMeshesRef.current = list;
  }, [nodes]); // re-run when the GLTF nodes become available (or when avatar changes)

  // Rewrite lerpMorphTarget to only touch the cached meshes
  const lerpMorphTarget = (target, value, speed = 0.1) => {
    const meshes = morphMeshesRef.current;
    if (!meshes.length || !target) return;

    for (const { dict, infl } of meshes) {
      const idx = dict[target];
      if (idx === undefined) continue;
      // inline lerp to avoid temporary calls/allocations
      const cur = infl[idx];
      infl[idx] = cur + (value - cur) * speed;
    }
   try {
      if (isSetupMode) set({ [target]: value });
    } catch (e) {}

  };    
  // Blink logic
  const blinkRef = useRef({ closing: false, nextTime: 0 });
  useFrame((state, delta) => {
    if (!group.current) {
      return;
    }
    // If setup mode is enabled, skip blink logic
    if (isSetupMode) return; 

    const now = state.clock.elapsedTime * 1000;
    if (now > blinkRef.current.nextTime) {
        blinkRef.current.closing = !blinkRef.current.closing;
        // If just blinked, schedule reopen
        if (!blinkRef.current.closing) {
        blinkRef.current.nextTime = now + THREE.MathUtils.randInt(1000, 5000);
        } else {
        blinkRef.current.nextTime = now + 200; // blink duration
        }
    }
    // drive morph targets for blinking
    lerpMorphTarget("eyeBlinkLeft", blinkRef.current.closing ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blinkRef.current.closing ? 1 : 0, 0.5);
  });

  // Facial expressions and animations
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");


  useFrame(() => {
    // early exit if GLTF nodes not ready yet
    if (!nodes?.EyeLeft?.morphTargetDictionary) return;

    !isSetupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      })
    
    // Apply wink states (override blink)
    lerpMorphTarget("eyeBlinkLeft", winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", winkRight ? 1 : 0, 0.5);

    // LIPSYNC with audioRef
    if (isSetupMode) {
      return;
    }
    // If nothing is playing, relax
    if (!audioRef.current || audioRef.current.paused) {
      visemes.forEach((name) => lerpMorphTarget(name, 0, 0.25));
      return;
    }
    
    // Process & read current viseme
    try {
      lipsyncManager.processAudio();
    } catch (error) {
      console.error("Error processing audio:", error);
    }
    let viseme = lipsyncManager.viseme;
    if (typeof viseme === "number") viseme = index_to_letter[viseme] ?? "X";
    if (typeof viseme === "string" && !viseme.startsWith("viseme_")) viseme = letter_to_name[viseme] ?? null;

    const activeName = viseme;
    // Drive shapes
    visemes.forEach(name => {
      const isActive = name === activeName;
      lerpMorphTarget(name, isActive ? 1 : 0, isActive ? 0.2 : 0.3);
    });
  });


  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
        value: animation,
        options: animationClips.map(a => a.name), 
        onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    setupMode: {
      value: isSetupMode,
      onChange: (v) => setIsSetupMode(v),
    },

    logMorphTargetValues: button(() => {
      const dict = nodes?.EyeLeft?.morphTargetDictionary;
      const infl = nodes?.EyeLeft?.morphTargetInfluences;
      if (!dict || !infl) return;
      const emotionValues = {};
      Object.keys(dict).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value = infl[dict[key]];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });
  const [, set] = useControls(
    "MorphTarget",
    () => {
      const dict = nodes?.EyeLeft?.morphTargetDictionary;
      const infl = nodes?.EyeLeft?.morphTargetInfluences;
      if (!dict || !infl) return {}; // safe until model is ready

    return Object.fromEntries(
      Object.keys(dict).map((key) => [
        key,
        {
          label: key,
          value: infl[dict[key]] ?? 0,
          min: 0,
          max: 1,
          onChange: (val) => {
            if (isSetupMode) lerpMorphTarget(key, val, 1);
          },
        },
      ])
    );
    },
    [nodes, isSetupMode]
  );


  return (
      <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
          name="EyeLeft"
          geometry={nodes.EyeLeft.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeLeft.skeleton}
          morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
          name="EyeRight"
          geometry={nodes.EyeRight.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeRight.skeleton}
          morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
          name="Wolf3D_Head"
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Wolf3D_Skin}
          skeleton={nodes.Wolf3D_Head.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
          name="Wolf3D_Teeth"
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Wolf3D_Teeth}
          skeleton={nodes.Wolf3D_Teeth.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
          geometry={nodes.Wolf3D_Hair.geometry}
          material={materials.Wolf3D_Hair}
          skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Wolf3D_Body}
          skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={materials.Wolf3D_Outfit_Bottom}
          skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Wolf3D_Outfit_Footwear}
          skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={materials.Wolf3D_Outfit_Top}
          skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      </group>
  )
}

useGLTF.preload('/models/689efc72bf8e07103aba1faa.glb')
useGLTF.preload("/models/animations.glb");




